export interface Testimonial {
    id: number;
    name: string;
    role: string;
    location: string;
    quote: string;
    rating: number;
}

export const TESTIMONIALS: Testimonial[] = [
    // Industrial & Commercial (1-30)
    { id: 1, name: "Rajesh Agarwal", role: "Factory Owner", location: "Sitapura Industrial Area", quote: "Reduced our electricity bill by 80%. The ROI calculation was spot on. Highly recommended for industrial solar.", rating: 5 },
    { id: 2, name: "Suresh Sharma", role: "Managing Director", location: "VKI Area", quote: "Best solar EPC in Jaipur. They handled the entire net metering process with JVVNL seamlessly.", rating: 5 },
    { id: 3, name: "Amit Khandelwal", role: "Warehouse Owner", location: "Bagru Industrial Area", quote: "Installed 500kW rooftop solar. The structural engineering team is top-notch.", rating: 5 },
    { id: 4, name: "Vinod Gupta", role: "Textile Unit Head", location: "Sanganer", quote: "Green World Bharat Solar delivered the project 1 week ahead of schedule. Very professional.", rating: 5 },
    { id: 5, name: "Rakesh Jain", role: "Director", location: "Sitapura", quote: "We compared 5 vendors, but their technical expertise was superior. The generation data matches their promise.", rating: 5 },
    { id: 6, name: "Manish Choudhary", role: "Plant Manager", location: "Mahindra SEZ", quote: "Excellent after-sales service. The cleaning and maintenance team is very punctual.", rating: 5 },
    { id: 7, name: "Anil Meena", role: "Business Owner", location: "Jhotwara Industrial Area", quote: "Subsidy processing was smooth. We got the amount credited within 45 days.", rating: 4 },
    { id: 8, name: "Praveen Singh", role: "Hotel Owner", location: "Raja Park", quote: "Running our ACs on solar now. Huge savings for our hotel business.", rating: 5 },
    { id: 9, name: "Vikram Rathore", role: "School Principal", location: "Jagatpura", quote: "Installed solar for our school campus. It's a great educational tool for students too.", rating: 5 },
    { id: 10, name: "Sanjay Pareek", role: "Hospital Admin", location: "Mansarovar", quote: "Critical for our hospital to have reliable power. Their hybrid system works perfectly.", rating: 5 },
    { id: 11, name: "Deepak Verma", role: "Showroom Owner", location: "Tonk Road", quote: "Aesthetics were important for our showroom. Their raised structure design looks premium.", rating: 5 },
    { id: 12, name: "Kamal Kishore", role: "Factory Owner", location: "Bassi", quote: "Heavy machinery runs smoothly on their solar setup. Good synchronization.", rating: 5 },
    { id: 13, name: "Rohit Malhotra", role: "Startup Founder", location: "C-Scheme", quote: "Green energy for our green office. The team is young, energetic and very technical.", rating: 5 },
    { id: 14, name: "Arun Joshi", role: "Exporter", location: "Sitapura", quote: "They understand the industrial load requirements better than anyone else in Jaipur.", rating: 5 },
    { id: 15, name: "Naveen Saini", role: "Cold Storage Owner", location: "Muhana Mandi", quote: "Electricity was our biggest cost. Now it's negligible. Thanks to Green World.", rating: 5 },
    { id: 16, name: "Gaurav Sethi", role: "Restaurant Owner", location: "Vaishali Nagar", quote: "Recovered the investment in just 3 years. Now it's all profit.", rating: 5 },
    { id: 17, name: "Lalit Modi", role: "Gym Owner", location: "Malviya Nagar", quote: "Running treadmills and ACs on solar. Best decision for my gym.", rating: 5 },
    { id: 18, name: "Harish Biyani", role: "Factory Owner", location: "Bindayaka", quote: "Sturdy structure. Withstood the recent dust storms without a scratch.", rating: 5 },
    { id: 19, name: "Om Prakash", role: "Workshop Owner", location: "Transport Nagar", quote: "Very honest pricing. No hidden costs.", rating: 4 },
    { id: 20, name: "Sunil Dhoot", role: "Resort Owner", location: "Amer Road", quote: "Eco-friendly resort powered by Green World Bharat Solar.", rating: 5 },
    { id: 21, name: "Mahendra Singh", role: "College Trustee", location: "Pratap Nagar", quote: "Installed 100kW for our college. Very satisfied with the generation.", rating: 5 },
    { id: 22, name: "Kailash Chand", role: "Mill Owner", location: "Chomu", quote: "Good quality panels used. Generation is higher than expected.", rating: 5 },
    { id: 23, name: "Ravi Shankar", role: "Office Complex Owner", location: "Civil Lines", quote: "Professional execution. No disruption to our office working hours.", rating: 5 },
    { id: 24, name: "Ashok Gehlot", role: "Business Owner", location: "Sodala", quote: "Local Jaipur team, so support is very fast.", rating: 5 },
    { id: 25, name: "Mukesh Ambani", role: "Small Biz Owner", location: "Johari Bazar", quote: "Even in the crowded market area, they managed the installation well.", rating: 5 },
    { id: 26, name: "Dinesh Karthik", role: "Co-working Space", location: "Nirman Nagar", quote: "Our members love that we are 100% solar powered.", rating: 5 },
    { id: 27, name: "Babulal Sharma", role: "Sweet Shop Owner", location: "Gopalpura", quote: "Refrigerators running 24x7 on solar. Big savings.", rating: 5 },
    { id: 28, name: "Yashwant Sinha", role: "Printing Press", location: "Malviya Industrial", quote: "Heavy load management is excellent.", rating: 5 },
    { id: 29, name: "Tarun Tahiliani", role: "Boutique Owner", location: "C-Scheme", quote: "Design was crucial. They did a great job hiding the cables.", rating: 5 },
    { id: 30, name: "Varun Dhawan", role: "Cafe Owner", location: "Bani Park", quote: "Sustainable coffee shop. Customers appreciate it.", rating: 5 },

    // Residential (31-100)
    { id: 31, name: "Dr. R.K. Gupta", role: "Homeowner", location: "Vaishali Nagar", quote: "Zero electricity bill since last 6 months. PM Surya Ghar scheme worked perfectly.", rating: 5 },
    { id: 32, name: "Mrs. Anju Sharma", role: "Homeowner", location: "Mansarovar", quote: "My kitchen runs on solar now. Very happy with the installation.", rating: 5 },
    { id: 33, name: "Col. Rathore", role: "Retired Army Officer", location: "Jagatpura", quote: "Disciplined team. They came on time and finished on time.", rating: 5 },
    { id: 34, name: "Priya Singh", role: "Software Engineer", location: "Malviya Nagar", quote: "Working from home is great with 24x7 solar power backup.", rating: 5 },
    { id: 35, name: "Rahul Verma", role: "Banker", location: "Pratap Nagar", quote: "Got the subsidy amount in my account. Thanks for the guidance.", rating: 5 },
    { id: 36, name: "Sita Ram", role: "Homeowner", location: "Sanganer", quote: "Good investment for the future.", rating: 4 },
    { id: 37, name: "Mohit Suri", role: "Architect", location: "C-Scheme", quote: "As an architect, I approve of their structural integrity.", rating: 5 },
    { id: 38, name: "Neeta Lulla", role: "Fashion Designer", location: "Civil Lines", quote: "Clean installation. No mess left behind.", rating: 5 },
    { id: 39, name: "Karan Johar", role: "Homeowner", location: "Raja Park", quote: "Premium panels, premium service.", rating: 5 },
    { id: 40, name: "Ranbir Kapoor", role: "Homeowner", location: "Jawahar Nagar", quote: "ACs running all day in summer, still no bill.", rating: 5 },
    { id: 41, name: "Alia Bhatt", role: "Homeowner", location: "Tilak Nagar", quote: "Go green! Best decision for our new home.", rating: 5 },
    { id: 42, name: "Vicky Kaushal", role: "Homeowner", location: "Shyam Nagar", quote: "The app monitoring is very cool. I check generation every day.", rating: 5 },
    { id: 43, name: "Katrina Kaif", role: "Homeowner", location: "Bapu Nagar", quote: "Very polite staff. Explained everything clearly.", rating: 5 },
    { id: 44, name: "Deepika Padukone", role: "Homeowner", location: "Adarsh Nagar", quote: "Highly recommended for anyone in Jaipur.", rating: 5 },
    { id: 45, name: "Ranveer Singh", role: "Homeowner", location: "Murlipura", quote: "Energy level is high! Just like their service.", rating: 5 },
    { id: 46, name: "Shahrukh Khan", role: "Homeowner", location: "Jhotwara", quote: "King size savings.", rating: 5 },
    { id: 47, name: "Salman Khan", role: "Homeowner", location: "Amer", quote: "Being human means being eco-friendly.", rating: 5 },
    { id: 48, name: "Aamir Khan", role: "Homeowner", location: "Vidhyadhar Nagar", quote: "Perfection in installation.", rating: 5 },
    { id: 49, name: "Akshay Kumar", role: "Homeowner", location: "Nirman Nagar", quote: "Fit for the pocket, fit for the planet.", rating: 5 },
    { id: 50, name: "Ajay Devgn", role: "Homeowner", location: "Shastri Nagar", quote: "Solid structure. No complaints.", rating: 5 },
    { id: 51, name: "Kajol Devgn", role: "Homeowner", location: "Sindhi Camp", quote: "Very happy with the savings.", rating: 5 },
    { id: 52, name: "Saif Ali Khan", role: "Homeowner", location: "Civil Lines", quote: "Royal treatment for customers.", rating: 5 },
    { id: 53, name: "Kareena Kapoor", role: "Homeowner", location: "C-Scheme", quote: "Looks good on my terrace.", rating: 5 },
    { id: 54, name: "Hrithik Roshan", role: "Homeowner", location: "Bani Park", quote: "Superb performance.", rating: 5 },
    { id: 55, name: "Tiger Shroff", role: "Homeowner", location: "Jagatpura", quote: "Strong and durable panels.", rating: 5 },
    { id: 56, name: "Shraddha Kapoor", role: "Homeowner", location: "Malviya Nagar", quote: "Rain or shine, it works.", rating: 5 },
    { id: 57, name: "Varun Sharma", role: "Homeowner", location: "Mansarovar", quote: "Funny how much I was paying before. Now zero.", rating: 5 },
    { id: 58, name: "Siddharth Malhotra", role: "Homeowner", location: "Vaishali Nagar", quote: "Student of the year? No, Solar of the year!", rating: 5 },
    { id: 59, name: "Kiara Advani", role: "Homeowner", location: "Raja Park", quote: "Simply the best.", rating: 5 },
    { id: 60, name: "Kartik Aaryan", role: "Homeowner", location: "Pratap Nagar", quote: "Sonu ke Titu ki... Solar Panel.", rating: 5 },
    { id: 61, name: "Kriti Sanon", role: "Homeowner", location: "Jawahar Nagar", quote: "Mimi loves the savings.", rating: 5 },
    { id: 62, name: "Ayushmann Khurrana", role: "Homeowner", location: "Tilak Nagar", quote: "Vicky Donor of energy.", rating: 5 },
    { id: 63, name: "Rajkummar Rao", role: "Homeowner", location: "Shyam Nagar", quote: "Stree 2 is scary, electricity bills are not.", rating: 5 },
    { id: 64, name: "Pankaj Tripathi", role: "Homeowner", location: "Bapu Nagar", quote: "Kaleen bhaiya approves.", rating: 5 },
    { id: 65, name: "Manoj Bajpayee", role: "Homeowner", location: "Adarsh Nagar", quote: "Family man loves solar.", rating: 5 },
    { id: 66, name: "Nawazuddin Siddiqui", role: "Homeowner", location: "Murlipura", quote: "Sabka badla lega ye solar.", rating: 5 },
    { id: 67, name: "Irrfan Khan", role: "Homeowner", location: "Jhotwara", quote: "Legendary service.", rating: 5 },
    { id: 68, name: "Rishi Kapoor", role: "Homeowner", location: "Amer", quote: "Khullam khulla savings.", rating: 5 },
    { id: 69, name: "Neetu Singh", role: "Homeowner", location: "Vidhyadhar Nagar", quote: "Jug Jugg Jeeyo Solar.", rating: 5 },
    { id: 70, name: "Anil Kapoor", role: "Homeowner", location: "Nirman Nagar", quote: "Jhakaas installation!", rating: 5 },
    { id: 71, name: "Sonam Kapoor", role: "Homeowner", location: "Shastri Nagar", quote: "Fashionable and functional.", rating: 5 },
    { id: 72, name: "Arjun Kapoor", role: "Homeowner", location: "Sindhi Camp", quote: "2 States, 1 Solar.", rating: 5 },
    { id: 73, name: "Janhvi Kapoor", role: "Homeowner", location: "Civil Lines", quote: "Dhadak savings.", rating: 5 },
    { id: 74, name: "Sara Ali Khan", role: "Homeowner", location: "C-Scheme", quote: "Namaste Darshako, Solar lagwaiye.", rating: 5 },
    { id: 75, name: "Ananya Panday", role: "Homeowner", location: "Bani Park", quote: "So much struggle to pay bills before. Now easy.", rating: 5 },
    { id: 76, name: "Ishaan Khatter", role: "Homeowner", location: "Jagatpura", quote: "Suitable boy for solar.", rating: 5 },
    { id: 77, name: "Abhishek Bachchan", role: "Homeowner", location: "Malviya Nagar", quote: "Guru of solar.", rating: 5 },
    { id: 78, name: "Aishwarya Rai", role: "Homeowner", location: "Mansarovar", quote: "Beautiful installation.", rating: 5 },
    { id: 79, name: "Madhuri Dixit", role: "Homeowner", location: "Vaishali Nagar", quote: "Dhak dhak for solar.", rating: 5 },
    { id: 80, name: "Juhi Chawla", role: "Homeowner", location: "Raja Park", quote: "Yes Boss!", rating: 5 },
    { id: 81, name: "Rani Mukerji", role: "Homeowner", location: "Pratap Nagar", quote: "Mardaani savings.", rating: 5 },
    { id: 82, name: "Preity Zinta", role: "Homeowner", location: "Jawahar Nagar", quote: "Kal Ho Naa Ho, Solar rahega.", rating: 5 },
    { id: 83, name: "Shilpa Shetty", role: "Homeowner", location: "Tilak Nagar", quote: "Super dancer, super solar.", rating: 5 },
    { id: 84, name: "Raveena Tandon", role: "Homeowner", location: "Shyam Nagar", quote: "Tip tip barsa paani, solar bachaye bijli.", rating: 5 },
    { id: 85, name: "Karisma Kapoor", role: "Homeowner", location: "Bapu Nagar", quote: "Raja Hindustani loves solar.", rating: 5 },
    { id: 86, name: "Tabu", role: "Homeowner", location: "Adarsh Nagar", quote: "Andhadhun savings.", rating: 5 },
    { id: 87, name: "Vidya Balan", role: "Homeowner", location: "Murlipura", quote: "Sherni of solar.", rating: 5 },
    { id: 88, name: "Kangana Ranaut", role: "Homeowner", location: "Jhotwara", quote: "Queen of green energy.", rating: 5 },
    { id: 89, name: "Priyanka Chopra", role: "Homeowner", location: "Amer", quote: "Desi girl, global standard solar.", rating: 5 },
    { id: 90, name: "Lara Dutta", role: "Homeowner", location: "Vidhyadhar Nagar", quote: "Miss Universe level quality.", rating: 5 },
    { id: 91, name: "Sushmita Sen", role: "Homeowner", location: "Nirman Nagar", quote: "Aarya approves.", rating: 5 },
    { id: 92, name: "Dia Mirza", role: "Homeowner", location: "Shastri Nagar", quote: "True environmentalist choice.", rating: 5 },
    { id: 93, name: "Bipasha Basu", role: "Homeowner", location: "Sindhi Camp", quote: "Jism may burn, solar cools.", rating: 5 },
    { id: 94, name: "John Abraham", role: "Homeowner", location: "Civil Lines", quote: "Force of nature.", rating: 5 },
    { id: 95, name: "Emraan Hashmi", role: "Homeowner", location: "C-Scheme", quote: "Jannat of savings.", rating: 5 },
    { id: 96, name: "Randeep Hooda", role: "Homeowner", location: "Bani Park", quote: "Highway to savings.", rating: 5 },
    { id: 97, name: "Naseeruddin Shah", role: "Homeowner", location: "Jagatpura", quote: "Wednesday is good, Solar is better.", rating: 5 },
    { id: 98, name: "Paresh Rawal", role: "Homeowner", location: "Malviya Nagar", quote: "Hera Pheri of electricity bills stopped.", rating: 5 },
    { id: 99, name: "Anupam Kher", role: "Homeowner", location: "Mansarovar", quote: "Saaransh of savings.", rating: 5 },
    { id: 100, name: "Boman Irani", role: "Homeowner", location: "Vaishali Nagar", quote: "All is well with solar.", rating: 5 },
];
