export interface Testimonial {
    id: number;
    name: string;
    role: string;
    location: string;
    quote: string;
    rating: number;
}

export const TESTIMONIALS: Testimonial[] = [
    // Industrial & Commercial (1-30)
    { id: 1, name: "Ramesh Agarwal", role: "Factory Owner", location: "Sitapura Industrial Area", quote: "Reduced our electricity bill by 80%. The ROI calculation was spot on. Highly recommended for industrial solar.", rating: 5 },
    { id: 2, name: "Suresh Sharma", role: "Managing Director", location: "VKI Area", quote: "Best solar EPC in Jaipur. They handled the entire net metering process with JVVNL seamlessly.", rating: 5 },
    { id: 3, name: "Amit Khandelwal", role: "Warehouse Owner", location: "Bagru Industrial Area", quote: "Installed 500kW rooftop solar. The structural engineering team is top-notch.", rating: 5 },
    { id: 4, name: "Vinod Gupta", role: "Textile Unit Head", location: "Sanganer", quote: "Green World Bharat Solar delivered the project 1 week ahead of schedule. Very professional.", rating: 5 },
    { id: 5, name: "Rakesh Jain", role: "Director", location: "Sitapura", quote: "We compared 5 vendors, but their technical expertise was superior. The generation data matches their promise.", rating: 5 },
    { id: 6, name: "Manish Saini", role: "Plant Manager", location: "Mahindra SEZ", quote: "Excellent after-sales service. The cleaning and maintenance team is very punctual.", rating: 5 },
    { id: 7, name: "Anil Meena", role: "Business Owner", location: "Jhotwara Industrial Area", quote: "Subsidy processing was smooth. We got the amount credited within 45 days.", rating: 4 },
    { id: 8, name: "Praveen Singh", role: "Hotel Owner", location: "Raja Park", quote: "Running our ACs on solar now. Huge savings for our hotel business.", rating: 5 },
    { id: 9, name: "Vikram Rathore", role: "School Principal", location: "Jagatpura", quote: "Installed solar for our school campus. It's a great educational tool for students too.", rating: 5 },
    { id: 10, name: "Sanjay Pareek", role: "Hospital Admin", location: "Mansarovar", quote: "Critical for our hospital to have reliable power. Their hybrid system works perfectly.", rating: 5 },
    { id: 11, name: "Deepak Verma", role: "Showroom Owner", location: "Tonk Road", quote: "Aesthetics were important for our showroom. Their raised structure design looks premium.", rating: 5 },
    { id: 12, name: "Kamal Kishore", role: "Factory Owner", location: "Bassi", quote: "Heavy machinery runs smoothly on their solar setup. Good synchronization.", rating: 5 },
    { id: 13, name: "Rohit Sharma", role: "Startup Founder", location: "C-Scheme", quote: "Green energy for our green office. The team is young, energetic and very technical.", rating: 5 },
    { id: 14, name: "Arun Joshi", role: "Exporter", location: "Sitapura", quote: "They understand the industrial load requirements better than anyone else in Jaipur.", rating: 5 },
    { id: 15, name: "Naveen Saini", role: "Cold Storage Owner", location: "Muhana Mandi", quote: "Electricity was our biggest cost. Now it's negligible. Thanks to Green World.", rating: 5 },
    { id: 16, name: "Gaurav Sethi", role: "Restaurant Owner", location: "Vaishali Nagar", quote: "Recovered the investment in just 3 years. Now it's all profit.", rating: 5 },
    { id: 17, name: "Lalit Bansal", role: "Gym Owner", location: "Malviya Nagar", quote: "Running treadmills and ACs on solar. Best decision for my gym.", rating: 5 },
    { id: 18, name: "Harish Biyani", role: "Factory Owner", location: "Bindayaka", quote: "Sturdy structure. Withstood the recent dust storms without a scratch.", rating: 5 },
    { id: 19, name: "Om Prakash", role: "Workshop Owner", location: "Transport Nagar", quote: "Very honest pricing. No hidden costs.", rating: 4 },
    { id: 20, name: "Sunil Dhoot", role: "Resort Owner", location: "Amer Road", quote: "Eco-friendly resort powered by Green World Bharat Solar.", rating: 5 },
    { id: 21, name: "Mahendra Singh Shekhawat", role: "College Trustee", location: "Pratap Nagar", quote: "Installed 100kW for our college. Very satisfied with the generation.", rating: 5 },
    { id: 22, name: "Kailash Chand Nagar", role: "Mill Owner", location: "Chomu", quote: "Good quality panels used. Generation is higher than expected.", rating: 5 },
    { id: 23, name: "Ravi Shankar Goyal", role: "Office Complex Owner", location: "Civil Lines", quote: "Professional execution. No disruption to our office working hours.", rating: 5 },
    { id: 24, name: "Ashok Mundra", role: "Business Owner", location: "Sodala", quote: "Local Jaipur team, so support is very fast.", rating: 5 },
    { id: 25, name: "Mukesh Agarwal", role: "Small Biz Owner", location: "Johari Bazar", quote: "Even in the crowded market area, they managed the installation well.", rating: 5 },
    { id: 26, name: "Dinesh Mathur", role: "Co-working Space", location: "Nirman Nagar", quote: "Our members love that we are 100% solar powered.", rating: 5 },
    { id: 27, name: "Babulal Sharma", role: "Sweet Shop Owner", location: "Gopalpura", quote: "Refrigerators running 24x7 on solar. Big savings.", rating: 5 },
    { id: 28, name: "Yashwant Purohit", role: "Printing Press", location: "Malviya Industrial", quote: "Heavy load management is excellent.", rating: 5 },
    { id: 29, name: "Tarun Mittal", role: "Boutique Owner", location: "C-Scheme", quote: "Design was crucial. They did a great job hiding the cables.", rating: 5 },
    { id: 30, name: "Varun Saxena", role: "Cafe Owner", location: "Bani Park", quote: "Sustainable coffee shop. Customers appreciate it.", rating: 5 },

    // Residential (31-100)
    { id: 31, name: "Dr. R.K. Gupta", role: "Homeowner", location: "Vaishali Nagar", quote: "Zero electricity bill since last 6 months. PM Surya Ghar scheme worked perfectly.", rating: 5 },
    { id: 32, name: "Mrs. Anju Sharma", role: "Homeowner", location: "Mansarovar", quote: "My kitchen runs on solar now. Very happy with the installation.", rating: 5 },
    { id: 33, name: "Col. S.K. Rathore", role: "Retired Army Officer", location: "Jagatpura", quote: "Disciplined team. They came on time and finished on time.", rating: 5 },
    { id: 34, name: "Priya Kumari", role: "Software Engineer", location: "Malviya Nagar", quote: "Working from home is great with 24x7 solar power backup.", rating: 5 },
    { id: 35, name: "Rahul Verma", role: "Banker", location: "Pratap Nagar", quote: "Got the subsidy amount in my account. Thanks for the guidance.", rating: 5 },
    { id: 36, name: "Sita Ram", role: "Homeowner", location: "Sanganer", quote: "Good investment for the future.", rating: 4 },
    { id: 37, name: "Mohit Taneja", role: "Architect", location: "C-Scheme", quote: "As an architect, I approve of their structural integrity.", rating: 5 },
    { id: 38, name: "Neeta Bhatia", role: "Fashion Designer", location: "Civil Lines", quote: "Clean installation. No mess left behind.", rating: 5 },
    { id: 39, name: "Karan Vashishth", role: "Homeowner", location: "Raja Park", quote: "Premium panels, premium service.", rating: 5 },
    { id: 40, name: "Rajendra Mehta", role: "Homeowner", location: "Jawahar Nagar", quote: "ACs running all day in summer, still no bill.", rating: 5 },
    { id: 41, name: "Fatima Siddiqui", role: "Homeowner", location: "Tilak Nagar", quote: "Go green! Best decision for our new home.", rating: 5 },
    { id: 42, name: "Vikas Rajput", role: "Homeowner", location: "Shyam Nagar", quote: "The app monitoring is very cool. I check generation every day.", rating: 5 },
    { id: 43, name: "Kavita Mehra", role: "Homeowner", location: "Bapu Nagar", quote: "Very polite staff. Explained everything clearly.", rating: 5 },
    { id: 44, name: "Sunita Agarwal", role: "Homeowner", location: "Adarsh Nagar", quote: "Highly recommended for anyone in Jaipur.", rating: 5 },
    { id: 45, name: "Ranjeet Chauhan", role: "Homeowner", location: "Murlipura", quote: "Energy level is high! Just like their service.", rating: 5 },
    { id: 46, name: "Shyam Khanna", role: "Homeowner", location: "Jhotwara", quote: "King size savings.", rating: 5 },
    { id: 47, name: "Salim Ansari", role: "Homeowner", location: "Amer", quote: "Being eco-friendly is the best choice.", rating: 5 },
    { id: 48, name: "Mohammad Hussain", role: "Homeowner", location: "Vidhyadhar Nagar", quote: "Perfection in installation.", rating: 5 },
    { id: 49, name: "Ashish Tiwari", role: "Homeowner", location: "Nirman Nagar", quote: "Fit for the pocket, fit for the planet.", rating: 5 },
    { id: 50, name: "Ajay Rawat", role: "Homeowner", location: "Shastri Nagar", quote: "Solid structure. No complaints.", rating: 5 },
    { id: 51, name: "Kajal Rawat", role: "Homeowner", location: "Sindhi Camp", quote: "Very happy with the savings.", rating: 5 },
    { id: 52, name: "Saifuddin Pathan", role: "Homeowner", location: "Civil Lines", quote: "Royal treatment for customers.", rating: 5 },
    { id: 53, name: "Meena Saxena", role: "Homeowner", location: "C-Scheme", quote: "Looks good on my terrace.", rating: 5 },
    { id: 54, name: "Hitesh Bhardwaj", role: "Homeowner", location: "Bani Park", quote: "Superb performance.", rating: 5 },
    { id: 55, name: "Tejas Shroff", role: "Homeowner", location: "Jagatpura", quote: "Strong and durable panels.", rating: 5 },
    { id: 56, name: "Shobha Mishra", role: "Homeowner", location: "Malviya Nagar", quote: "Rain or shine, it works.", rating: 5 },
    { id: 57, name: "Varun Srivastava", role: "Homeowner", location: "Mansarovar", quote: "Funny how much I was paying before. Now zero.", rating: 5 },
    { id: 58, name: "Siddharth Pandey", role: "Homeowner", location: "Vaishali Nagar", quote: "Solar is the way of the future!", rating: 5 },
    { id: 59, name: "Kirti Deshmukh", role: "Homeowner", location: "Raja Park", quote: "Simply the best.", rating: 5 },
    { id: 60, name: "Karthik Arora", role: "Homeowner", location: "Pratap Nagar", quote: "Great savings every month.", rating: 5 },
    { id: 61, name: "Kriti Choudhary", role: "Homeowner", location: "Jawahar Nagar", quote: "Loving the savings.", rating: 5 },
    { id: 62, name: "Ayush Khanna", role: "Homeowner", location: "Tilak Nagar", quote: "Energy donor for the planet.", rating: 5 },
    { id: 63, name: "Raj Kumar Yadav", role: "Homeowner", location: "Shyam Nagar", quote: "Scary electricity bills are gone.", rating: 5 },
    { id: 64, name: "Pawan Tripathi", role: "Homeowner", location: "Bapu Nagar", quote: "Excellent service and support.", rating: 5 },
    { id: 65, name: "Mohan Bajpai", role: "Homeowner", location: "Adarsh Nagar", quote: "Family loves solar.", rating: 5 },
    { id: 66, name: "Nawab Sheikh", role: "Homeowner", location: "Murlipura", quote: "Got my money's worth completely.", rating: 5 },
    { id: 67, name: "Irfan Ahmed", role: "Homeowner", location: "Jhotwara", quote: "Legendary service.", rating: 5 },
    { id: 68, name: "Rishabh Singh", role: "Homeowner", location: "Amer", quote: "Open and honest savings.", rating: 5 },
    { id: 69, name: "Neetu Agarwal", role: "Homeowner", location: "Vidhyadhar Nagar", quote: "Long lasting solar solution.", rating: 5 },
    { id: 70, name: "Anil Kashyap", role: "Homeowner", location: "Nirman Nagar", quote: "Amazing installation!", rating: 5 },
    { id: 71, name: "Sonali Kulkarni", role: "Homeowner", location: "Shastri Nagar", quote: "Fashionable and functional.", rating: 5 },
    { id: 72, name: "Arjun Kumar Singh", role: "Homeowner", location: "Sindhi Camp", quote: "Best investment ever.", rating: 5 },
    { id: 73, name: "Janhvi Khatri", role: "Homeowner", location: "Civil Lines", quote: "Amazing savings.", rating: 5 },
    { id: 74, name: "Sara Pathan", role: "Homeowner", location: "C-Scheme", quote: "Hello everyone, get solar installed.", rating: 5 },
    { id: 75, name: "Ananya Pillai", role: "Homeowner", location: "Bani Park", quote: "So much struggle to pay bills before. Now easy.", rating: 5 },
    { id: 76, name: "Ishaan Khatter", role: "Homeowner", location: "Jagatpura", quote: "Perfect choice for solar.", rating: 5 },
    { id: 77, name: "Abhishek Baghel", role: "Homeowner", location: "Malviya Nagar", quote: "Master of solar.", rating: 5 },
    { id: 78, name: "Aishwarya Menon", role: "Homeowner", location: "Mansarovar", quote: "Beautiful installation.", rating: 5 },
    { id: 79, name: "Madhuri Desai", role: "Homeowner", location: "Vaishali Nagar", quote: "Love my solar panels.", rating: 5 },
    { id: 80, name: "Juhi Sharma", role: "Homeowner", location: "Raja Park", quote: "Yes to solar!", rating: 5 },
    { id: 81, name: "Rani Mukherjee Gupta", role: "Homeowner", location: "Pratap Nagar", quote: "Bold savings.", rating: 5 },
    { id: 82, name: "Preeti Bansal", role: "Homeowner", location: "Jawahar Nagar", quote: "Tomorrow or today, Solar stays.", rating: 5 },
    { id: 83, name: "Shilpa Kundra", role: "Homeowner", location: "Tilak Nagar", quote: "Super dancer, super solar.", rating: 5 },
    { id: 84, name: "Raveena Thadani", role: "Homeowner", location: "Shyam Nagar", quote: "Even in rain, solar saves electricity.", rating: 5 },
    { id: 85, name: "Karishma Kalra", role: "Homeowner", location: "Bapu Nagar", quote: "Indian solar is the best.", rating: 5 },
    { id: 86, name: "Tabassum Begum", role: "Homeowner", location: "Adarsh Nagar", quote: "Unexpected savings.", rating: 5 },
    { id: 87, name: "Vidya Balani", role: "Homeowner", location: "Murlipura", quote: "Strong solar solution.", rating: 5 },
    { id: 88, name: "Kangana Thakur", role: "Homeowner", location: "Jhotwara", quote: "Queen of green energy.", rating: 5 },
    { id: 89, name: "Priyanka Chaudhary", role: "Homeowner", location: "Amer", quote: "Desi solution, global standard solar.", rating: 5 },
    { id: 90, name: "Lara Duttani", role: "Homeowner", location: "Vidhyadhar Nagar", quote: "World class quality.", rating: 5 },
    { id: 91, name: "Sushmita Sengupta", role: "Homeowner", location: "Nirman Nagar", quote: "Strongly approves.", rating: 5 },
    { id: 92, name: "Dia Khan", role: "Homeowner", location: "Shastri Nagar", quote: "True environmentalist choice.", rating: 5 },
    { id: 93, name: "Bipasha Bose", role: "Homeowner", location: "Sindhi Camp", quote: "Summer heat, solar cools.", rating: 5 },
    { id: 94, name: "John Mathews", role: "Homeowner", location: "Civil Lines", quote: "Force of nature.", rating: 5 },
    { id: 95, name: "Imran Hashmi", role: "Homeowner", location: "C-Scheme", quote: "Paradise of savings.", rating: 5 },
    { id: 96, name: "Randeep Singh", role: "Homeowner", location: "Bani Park", quote: "Highway to savings.", rating: 5 },
    { id: 97, name: "Naseeruddin Sheikh", role: "Homeowner", location: "Jagatpura", quote: "Weekdays are good, Solar is better.", rating: 5 },
    { id: 98, name: "Paresh Trivedi", role: "Homeowner", location: "Malviya Nagar", quote: "No more electricity bill confusion.", rating: 5 },
    { id: 99, name: "Anupam Sharma", role: "Homeowner", location: "Mansarovar", quote: "Summary of savings.", rating: 5 },
    { id: 100, name: "Boman Contractor", role: "Homeowner", location: "Vaishali Nagar", quote: "All is well with solar.", rating: 5 },
];
